[colors.primary]
background = '#1D2021' # base
foreground = '#D4BE98' # text
# Bright and dim foreground colors
dim_foreground = '#D4BE98' # text
bright_foreground = '#D4BE98' # text

# Cursor colors
[colors.cursor]
text = '#1D2021' # base
cursor = '#EA6962' # rosewater

[colors.vi_mode_cursor]
text = '#1D2021' # base
cursor = '#7DAEA3' # lavender

# Search colors
[colors.search.matches]
foreground = '#1D2021' # base
background = '#A69372' # subtext0

[colors.search.focused_match]
foreground = '#1D2021' # base
background = '#A9B665' # green

[colors.footer_bar]
foreground = '#1D2021' # base
background = '#A69372' # subtext0

# Keyboard regex hints
[colors.hints.start]
foreground = '#1D2021' # base
background = '#F9E2AF' # yellow

[colors.hints.end]
foreground = '#1D2021' # base
background = '#A69372' # subtext0

# Selection colors
[colors.selection]
text = '#1D2021' # base
background = '#EA6962' # rosewater

# Normal colors
[colors.normal]
black = '#2A2D2E' # surface1
red = '#EA6962' # red
green = '#A9B665' # green
yellow = '#D8A657' # yellow
blue = '#7DAEA3' # blue
magenta = '#D3869B' # pink
cyan = '#89B482' # teal
white = '#BDAE8B' # subtext1

# Bright colors
[colors.bright]
black = '#4B4F51' # surface2
red = '#EA6962' # red
green = '#A9B665' # green
yellow = '#D8A657' # yellow
blue = '#7DAEA3' # blue
magenta = '#D3869B' # pink
cyan = '#89B482' # teal
white = '#A69372' # subtext0

# Dim colors
[colors.dim]
black = '#2A2D2E' # surface1
red = '#EA6962' # red
green = '#A9B665' # green
yellow = '#D8A657' # yellow
blue = '#7DAEA3' # blue
magenta = '#D3869B' # pink
cyan = '#89B482' # teal
white = '#BDAE8B' # subtext1
