
[cursor]
style = "beam"
unfocused_hollow = true

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.offset]
x = 0
y = 0

[window]
dynamic_padding = false
decorations = "None"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[general]
import = [
    "~/.config/alacritty/themes/catppuccin_mocha.toml"
]

